"""Initial migration

Revision ID: 76734fdb43e6
Revises: 
Create Date: 2024-10-27 15:33:09.483333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76734fdb43e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tb_clothes_clo_name'), 'tb_clothes', ['clo_name'], unique=False)
    op.create_index(op.f('ix_tb_user_user_id'), 'tb_user', ['user_id'], unique=False)
    op.create_index(op.f('ix_tb_user_user_name'), 'tb_user', ['user_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_user_user_name'), table_name='tb_user')
    op.drop_index(op.f('ix_tb_user_user_id'), table_name='tb_user')
    op.drop_index(op.f('ix_tb_clothes_clo_name'), table_name='tb_clothes')
    # ### end Alembic commands ###
