"""Add user_gender to User model

Revision ID: 7fe7098ab66c
Revises: cbcc16a26b0f
Create Date: 2024-11-08 14:00:11.992948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe7098ab66c'
down_revision: Union[str, None] = 'cbcc16a26b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_user', sa.Column('user_gender', sa.Enum('male', 'female', name='genderenum'), nullable=False, comment='사용자 성별'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_user', 'user_gender')
    # ### end Alembic commands ###
