"""Initial migration

Revision ID: 9f38d7105145
Revises: 76734fdb43e6
Create Date: 2024-10-28 15:25:36.179290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f38d7105145'
down_revision: Union[str, None] = '76734fdb43e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_clothes',
    sa.Column('clo_idx', sa.Integer(), autoincrement=True, nullable=False, comment='옷 식별자'),
    sa.Column('clo_name', sa.String(length=100), nullable=False, comment='옷 제품명'),
    sa.Column('clo_desc', sa.Text(), nullable=False, comment='옷 설명'),
    sa.Column('clo_price', sa.Integer(), nullable=False, comment='옷 가격'),
    sa.Column('clo_3d', sa.String(length=1000), nullable=True, comment='옷 3D 이미지'),
    sa.Column('clo_img1', sa.String(length=1000), nullable=False, comment='옷 사진1'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False, comment='등록 일자'),
    sa.PrimaryKeyConstraint('clo_idx')
    )
    op.create_index(op.f('ix_tb_clothes_clo_name'), 'tb_clothes', ['clo_name'], unique=False)
    op.create_table('tb_user',
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='사용자 아이디'),
    sa.Column('user_pw', sa.String(length=100), nullable=False, comment='사용자 비밀번호'),
    sa.Column('user_name', sa.String(length=50), nullable=False, comment='사용자 이름'),
    sa.Column('user_email', sa.String(length=50), nullable=False, comment='사용자 이메일'),
    sa.Column('joined_at', sa.TIMESTAMP(), nullable=False, comment='가입 일자'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email')
    )
    op.create_index(op.f('ix_tb_user_user_id'), 'tb_user', ['user_id'], unique=False)
    op.create_index(op.f('ix_tb_user_user_name'), 'tb_user', ['user_name'], unique=False)
    op.create_table('tb_avatar',
    sa.Column('avatar_idx', sa.Integer(), autoincrement=True, nullable=False, comment='아바타 식별자'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='사용자 아이디'),
    sa.Column('img_rname', sa.String(length=10000), nullable=False, comment='원본 이미지 파일명'),
    sa.Column('img_path', sa.String(length=1000), nullable=False, comment='2D 이미지 파일 경로'),
    sa.Column('img_size', sa.Integer(), nullable=False, comment='이미지 파일 크기'),
    sa.Column('img_ext', sa.String(length=10), nullable=False, comment='이미지 파일 확장자'),
    sa.Column('avatar_path', sa.String(length=1000), nullable=True, comment='생성된 3D 아바타 파일 경로'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False, comment='등록 일자'),
    sa.Column('height', sa.Integer(), nullable=True, comment='신장'),
    sa.Column('weight', sa.Integer(), nullable=True, comment='체중'),
    sa.Column('chest_circumference', sa.Float(), nullable=True, comment='가슴둘레'),
    sa.Column('waist_circumference', sa.Float(), nullable=True, comment='허리둘레'),
    sa.Column('hip_circumference', sa.Float(), nullable=True, comment='엉덩이둘레'),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.user_id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('avatar_idx')
    )
    op.create_table('tb_fitting',
    sa.Column('fitting_idx', sa.Integer(), autoincrement=True, nullable=False, comment='피팅 식별자'),
    sa.Column('avatar_idx', sa.Integer(), nullable=False, comment='아바타 식별자'),
    sa.Column('clo_idx', sa.Integer(), nullable=False, comment='옷 식별자'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False, comment='피팅 날짜'),
    sa.ForeignKeyConstraint(['avatar_idx'], ['tb_avatar.avatar_idx'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['clo_idx'], ['tb_clothes.clo_idx'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('fitting_idx')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_fitting')
    op.drop_table('tb_avatar')
    op.drop_index(op.f('ix_tb_user_user_name'), table_name='tb_user')
    op.drop_index(op.f('ix_tb_user_user_id'), table_name='tb_user')
    op.drop_table('tb_user')
    op.drop_index(op.f('ix_tb_clothes_clo_name'), table_name='tb_clothes')
    op.drop_table('tb_clothes')
    # ### end Alembic commands ###
