"""Alter foreign key on clo_idx to cascade on delete

Revision ID: cbcc16a26b0f
Revises: eaae7f54329e
Create Date: 2024-11-04 16:37:50.956106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cbcc16a26b0f'
down_revision: Union[str, None] = 'eaae7f54329e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_avatar', 'img_rname',
               existing_type=mysql.VARCHAR(length=10000),
               type_=sa.String(length=1000),
               existing_comment='원본 이미지 파일명',
               existing_nullable=False)
    op.drop_constraint('tb_fitting_ibfk_2', 'tb_fitting', type_='foreignkey')
    op.create_foreign_key(None, 'tb_fitting', 'tb_clothes', ['clo_idx'], ['clo_idx'], onupdate='RESTRICT', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_fitting', type_='foreignkey')
    op.create_foreign_key('tb_fitting_ibfk_2', 'tb_fitting', 'tb_clothes', ['clo_idx'], ['clo_idx'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.alter_column('tb_avatar', 'img_rname',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=10000),
               existing_comment='원본 이미지 파일명',
               existing_nullable=False)
    # ### end Alembic commands ###
